version: '3.8'
services:


  #base de datos de reservations
  reservations-db:
    image: postgres:16-alpine
    container_name: reservations-db
    environment:
      POSTGRES_DB: reservations_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Uisrael.
    ports:
      - "5433:5432"
    volumes:
      - reservations-db-data:/var/lib/postgresql/data
    networks:
      - microservicios-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservations_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  reservations-service:
    build:
      context: ./svc-reservations
      dockerfile: Dockerfile
    container_name: reservations-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reservations-db:5432/reservations_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Uisrael.
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    networks:
      - microservicios-network
    depends_on:
      reservations-db:
        condition: service_healthy
volumes:
  reservations-db-data:
networks:
  microservicios-network:
    driver: bridge


