spring.application.name=svc-reservations
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/reservations_db
spring.datasource.username=postgres
spring.datasource.password=Uisrael.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health,info

#URL DE svc-rooms
rooms.service.url=http://rooms-service:8081

#Resilience- circuit breaker
resilience4j.circuitbreaker.instances.catalogService.sliding-window-size=5
resilience4j.circuitbreaker.instances.catalogService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.catalogService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.catalogService.permitted-number-of-calls-in-half-open-state=3

#Retry
resilience4j.retry.instances.catalogService.max-attempts=3
resilience4j.retry.instances.catalogService.wait-duration=2s

# timeout
resilience4j.timelimiter.instances.catalogService.timeout-duration=3s